import { Container } from "@/shared/components/shared/container"
import { Header } from "@/shared/components/shared/header"
import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'MTG shop | Корзина',
    description: 'Generated by Next.js',
}

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
    return <main className="min-h-screen bg-[#f4eeee]">
        <Container>
            <Header hasSearch={false} hasCart={false} classname="border-gray-200"/>
            {children}
        </Container>
    </main>
}
